config/routes.rb
PotentialPresents::Application.routes.draw do
	root to: 'static_pages#home'

  resources :users
	match '/signup', to: 'users#new'

  resources :presents
	match '/newpresent', to: 'presents#new'

	resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
	

end

app/models/present.rb
class Present < ActiveRecord::Base
  attr_accessible :content, :user_id, :cost, :link, :purchased, :ordered

	validates :content, presence: true
	validates :link, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
	has_secure_password

	has_many :presents

	VALID_NAME = /\A[a-zA-Z0-9_]{2,30}\Z/
  validates :name, presence: true, length: { maximum: 50 }, format: { with: VALID_NAME }, uniqueness: { case_sensitive: false }
	validates :email, presence: true, uniqueness: { case_sensitive: false }
	validates :password_confirmation, presence: true
	validates :password, presence: true, length: { minimum: 6 }

	before_save { self.email.downcase! } 
	before_save { self.name = self.name.slice(0,1).capitalize + self.name.slice(1..-1) }
  before_save :create_remember_token

	def to_param
		name
	end


  private
	  def create_remember_token
	    self.remember_token = SecureRandom.hex
	  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update]

  # GET /presents
  # GET /presents.json
  def index
    @presents = Present.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @presents }
    end
  end

  # GET /presents/1
  # GET /presents/1.json
  def show
    @present = Present.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @present }
    end
  end

  # GET /presents/new
  # GET /presents/new.json
  def new
    @present = Present.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @present }
    end
  end

  # GET /presents/1/edit
  def edit
    @present = Present.find(params[:id])
  end

  # POST /presents
  # POST /presents.json
  def create
		@user = current_user
    @present = @user.presents.new(params[:present])

    respond_to do |format|
      if @present.save
        format.html { redirect_to @present, notice: 'Link was successfully created.' }
        format.json { render json: @present, status: :created, location: @present }
      else
        format.html { render action: "new" }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /presents/1
  # PUT /presents/1.json
  def update
    @present = Present.find(params[:id])

    respond_to do |format|
      if @present.update_attributes(params[:present])
        format.html { redirect_to @present, notice: 'Present was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present = Present.find(params[:id])
    @present.destroy

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

	private
		def set_not_purchased
			self.purchased = 0
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
  end

  def create
    user = User.find_by_name(params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		@Presents = Present.all.reverse.take(20)

		if signed_in?
			@user = current_user
		end
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_user, only: [:index, :edit, :update]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_name(params[:id])
		@Presents = Present.where("user_id=?",@user.id).reverse.take(20)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by_name(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
				sign_in @user
        format.html { redirect_to @user, notice: 'Account created successfully.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, :notice => "Please sign in."
    end
  end

  def correct_user
    @user = User.find_by_name(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="masthead">
	<ul class="nav nav-pills pull-right">
		<% if signed_in? %>
			<li><%= link_to current_user.name, current_user %></li>
		<% end %>
      <li><%= link_to "Home", root_path %></li>
    <% if signed_in? %>
      <li id="fat-menu" class="dropdown">
      	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
        	Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
           <li><%= link_to "My Links", current_user %></li>
		  		 <li><%= link_to "New Link", newpresent_path %></li>
           <li><%= link_to "Settings", edit_user_path(current_user) %></li>
           <li class="divider"></li>
           <li><%= link_to "Sign out", signout_path, method: "delete" %> </li>
				</ul>
      </li>
    <% else %>
      <li><%= link_to "Sign up", signup_path %></li>
			<li id="fat-menu" class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<%= simple_form_for :session, url: sessions_path do |f| %>
							<%= f.input :name, label: false, wrapper_html: { id: "nameInput", class: "signInDrop" } %>
							<%= f.input :password, label: false, wrapper_html: { id: "passInput", class: "signInDrop" } %>
						  <%= f.button :submit, "Sign in", class: "btn-small loginbtn" %>
						<% end %>
					</li>
				</ul>
			</li>
    <% end %>
	</ul>
	<h3 class="muted">WishLinks</h3>
</div>

<hr width="700">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>WishLinks</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

	</head>
	<body>

		<div class="container-narrow">

			<%= render 'layouts/header' %>
			<%= yield %>

			<!--		<%= debug(params) if Rails.env.development? %> --!>
		</div>	
	</body>
</html>

app/views/presents/_form.html.erb
<%= simple_form_for @present, html: { class: "form-horizontal" } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.input :content, label: 'You would like this', hint: 'Give your link a name' %>
	<%= f.input :link, label: 'Link', hint: 'Paste your link in here' %>
	<%= f.input :cost, label: 'Rough price', hint: 'No need for a $ symbol' %>
	<%= f.hidden_field :purchased, value: '0' %> 
  <%= f.hidden_field :ordered, value: '0' %>

	<%= f.button :submit, "List", class: "btn btn-small" %>
<% end %>

app/views/presents/edit.html.erb
<h3>Edit Link</h3>

<%= render 'form' %>

app/views/presents/index.html.erb
<h1>Listing presents</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @presents.each do |present| %>
  <tr>
    <td><%= present.content %></td>
    <td><%= present.user_id %></td>
    <td><%= link_to 'Show', present %></td>
    <td><%= link_to 'Edit', edit_present_path(present) %></td>
    <td><%= link_to 'Destroy', present, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Present', new_present_path %>

app/views/presents/new.html.erb
<h3>Create a new Link</h3>

<%= render 'form' %>

app/views/presents/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @present.content %></h3>
<% @user = User.find_by_id(@present.user_id) %>

<% if @present.purchased == 0 %>
	<p>
		<%= link_to @user.name, user_path(@user.id) %> wouldn't mind if someone bought them <%= link_to @present.content, @present.link, target: "_blank" %>.<% if @present.cost == nil %> No idea how much it costs though :(. <% else %> It roughly costs $<%= @present.cost %> so why not! <% end %> 
	</p>
<% else %>
		<%= link_to @user.name, user_path(@user.id) %> was kindly bought <%= link_to @present.content, @present.link, target: "_blank" %>.<% if @present.cost == nil %> No idea how much it cost though :(. <% else %> Some kind person paid $<%= @present.cost %> for it! <% end %>
<% end %>

<p>
	<% if current_user?(@user) %>
		<%= link_to "edit", edit_present_path(@present), class: "btn btn-mini" %> 
    <%= link_to "delete", @present, method: :delete, data: { confirm: "You sure?" }, title: @present.content, class: "btn btn-mini" %>
	<% end %>
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
		<strong>Hold on there!</strong> Looks like you might have missed something.
	</div>
<% end %>

app/views/shared/_item_buttons.html.erb
<% if signed_in? %>
	<%= link_to raw('<i class="icon-shopping-cart"></i>'), list_item.link, target: "_blank", class: "tip-info", title: "View external link" %>
<% else %>
  <%= link_to raw('<i class="icon-shopping-cart"></i>'), list_item.link, target: "_blank", class: "tip-info", title: "Signup to tell others you are buying this" %>
<% end %>

<% if current_user?(list_item.user) %>
	<%= link_to raw('<i class="icon-pencil"></i>'), edit_present_path(list_item), class: "edit", title: "Edit this entry" %>
  <%= link_to raw('<i class="icon-trash"></i>'), list_item, method: :delete, data: { confirm: "You sure?" }, title: "Delete this entry", class: "delete" %>
	<% if list_item.purchased != 1 %>
		<%= link_to raw('<i class="icon-tag"></i>'), present_path(list_item, present: {purchased: "1"}), method: 'put', class: "tip-info", title: "Tag this link owned" %>
	<% else %>
		<%= link_to raw('<i class="icon-gift"></i>'), '#', class: "tip-info", title: "You have this!" %>
	<% end %>
<% else %>
	<% if list_item.ordered != 1 && list_item.purchased != 1 %>
		<%= link_to raw('<i class="icon-envelope"></i>'), present_path(list_item, present: {ordered: 1}), method: 'put', class: "tip-info", title: "Mark this link ordered" %>
	<% elsif list_item.purchased == 1 %>
		<%= link_to raw('<i class="icon-gift"></i>'), '#', class: "tip-info", title: "Link already gifted" %>
	<% else %>
		<%= link_to raw('<i class="icon-warning-sign"></i>'), '#', class: "tip-info", title: "Link has already been ordered" %>
	<% end %>
<% end %>

app/views/shared/_list.html.erb
<% if signed_in? %>
<div class="present span6 offset1 capsule" id="new">
	<ul id="new">
		<span class="content">
			<%= form_for :present, action: 'new', url: presents_path, class: "test-form" do |f| %>
				<strong>You would like this:</strong>
				<%= f.text_field :content, id: "linkNameInput", class: "freshCapsule" %>
				<strong> which can be found here:</strong>
				<%= f.text_field :link, id: "linkInput", class: "freshCapsule" %>
        <%= f.hidden_field :purchased, value: '0' %>
				<%= f.submit "List", class: "btn btn-mini" %>
			<% end %>
		</span>
	</ul>
</div>
<% end %>

<% if @Presents.any? %>
  <%= render partial: 'shared/list_item', collection: @Presents %>
<% end %>

app/views/shared/_list_item.html.erb
<% if list_item.content.length > 14 then
	link_name = list_item.content[0..9]
	link_name << "..."
	tool_tip_name = list_item.content
else
	link_name = list_item.content
end %>

<div class="present span6 offset1 capsule" id="<% if list_item.purchased == 1 %>have<% else %>want<% end %>">
	<ul id="<%= list_item.id %>">
		<span class="content">
			<% if list_item.purchased == 0 %>
				<strong>
					<% if current_user?(list_item.user) %>
						<%= link_to "You", list_item.user %>
					<% else %>
						<%= link_to list_item.user.name, list_item.user %>
					<% end %>
						 would like this: <%= link_to link_name, '#', title: tool_tip_name, class: "long-name" %></strong><font color="#999"> - <%= time_ago_in_words(list_item.created_at) %> ago</font>
			<% else %>
				<strong>
					<% if current_user?(list_item.user) %>
            <%= link_to "You", list_item.user %>
          <% else %>
            <%= link_to list_item.user.name, list_item.user %>
          <% end %>
						received this: <%= link_to link_name, '#' %></strong><font color="#999"> - <%= time_ago_in_words(list_item.updated_at) %> ago</font>
			<% end %>
			<b class="caret" id="pointDown"></b>
	  </span>
		<div class="details">
			<%= render partial: 'shared/item_buttons', locals: { list_item: list_item} %>
		</div>
	</ul>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if !signed_in? %>
<div class="jumbotron">

	<div class="span8 welcome">
		<strong>Hi!</strong> I'm new to this kind of stuff - web design and magic - I'd be happy to hear any feedback you might have for the site or feature requests. <a href="https://plus.google.com/109159496881679410875/">g+ me</a>.
    <a href="#"><b class="caret feature" id="pointUp"></b></a>
	</div>

	<h1 id="randomHeader"></h1>
</div>
<% end %>

<div class="span8">
	<p>This is a simple wish list site. Feel free to browse other peoples links<% if !signed_in? %> or you can <%= link_to "signup", signup_path %> and start your own link list<% end %>. Currently we have <%= Present.count %> links between <%= User.count %> users. </p>
</div>

<br />

<%= render 'shared/list' %>

app/views/users/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_form.html.erb
<%= simple_form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :name, label: 'Username' %>
  <%= f.input :email, label: 'Email' %>
  <%= f.input :password, label: 'Password' %>
  <%= f.input :password_confirmation, label: 'Confirm password' %>

  <%= f.button :submit, "Update User", class: "btn btn-small" %>
<% end %>

app/views/users/edit.html.erb
<h3>Update your account</h3>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= simple_form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
	<%= f.input :name, label: 'Username', hint: 'One word, no special characters please.' %>
	<%= f.input :email, label: 'Email' %>
	<%= f.input :password, label: 'Password' %>
	<%= f.input :password_confirmation, label: 'Confirm password' %>

  <%= f.button :submit, "Create my account", class: "btn btn-small" %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %> has <%= pluralize(@user.presents.count, "Link", "Links") %>
      </h1>
    </section>
  </aside>

  <div class="span8">
		<% if @user.presents.empty? %>
			<% if current_user?(@user) %>
				<p>
					Awwwww, you don't have any links. <%= link_to 'Create', newpresent_path %> your first link.
				</p>
			<% else %>
				<p>
					How sad, this person doesn't have any links.
				</p>
			<% end %>
		<% else %>
		<% if current_user?(@user) %>
				<p>
					<%= link_to 'Add another link!', newpresent_path %>
				</p>
			<% end %>
		<p>
				<%= render 'shared/list' %>
			</p>
	<% end %>
	</div>
</div>